# Generated by Django 5.2.6 on 2025-10-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='realizado',
            field=models.BooleanField(default=False),
        ),
    ]
